#!/usr/bin/env bash
# S2 / AS-22, AS-31, INV-2, INV-5: retransmitted SYNs without answer and
# one-way UDP flows while the active set changes; RELATED ICMP errors from a
# LAN host and from the router for inbound traffic through an uplink outside
# the active set; path MTU discovery for a pinned outbound flow. Both families.
set -euo pipefail
P=s2; source "$(dirname "$0")/../lib/netns.sh"; source "$(dirname "$0")/s2lib.sh"
trap 'kill $(jobs -p) 2>/dev/null || true; topo_down' EXIT
topo_up
for f in 4 6; do ftr_install $f 1 2 3; done
portfwd_up
ip netns exec "$P-c" $PEER serve >/dev/null 2>&1 &
s2_nft 1 2 3
# The internet silently drops the test flows, so nothing is ever answered.
nsi nft add table inet blackhole
nsi nft add chain inet blackhole in '{ type filter hook prerouting priority 0; policy accept; }'
nsi nft add rule inet blackhole in tcp dport 9999 drop
nsi nft add rule inet blackhole in udp dport 9 drop

cap_start() { # cap_start FILTER: one tcpdump per uplink, router side
  local i
  for i in wana wanb wanc; do
    nsr tcpdump -lni "$i" "$1" >"/tmp/$P-cap-$i" 2>/dev/null & eval "CAP_$i=$!"
  done
  sleep 0.5
}
cap_stop() { local i p; sleep 0.3; for i in wana wanb wanc; do eval "p=\$CAP_$i"; kill "$p" 2>/dev/null || true; wait "$p" 2>/dev/null || true; done; }
cap_count() { local n=0 i; for i in wana wanb wanc; do n=$((n + $(grep -c . "/tmp/$P-cap-$i" || true))); done; echo $n; }
cap_on() { grep -c . "/tmp/$P-cap-$1" || true; }

echo "== AS-22: unanswered SYNs and one-way UDP while the active set changes"
cap_start "tcp dst port 9999 or udp dst port 9"
ip netns exec "$P-c" $S2TOOL syn 198.18.100.51 --port 9999 --count 10 --sport 41000 --duration 8 >/tmp/$P-syn4 & G1=$!
ip netns exec "$P-c" $S2TOOL syn 2001:db8:100::51 --port 9999 --count 10 --sport 41000 --duration 8 >/tmp/$P-syn6 & G2=$!
ip netns exec "$P-c" $S2TOOL stream 198.18.100.52 --port 9 --count 10 --sport 42000 --duration 8 --period 0.2 >/tmp/$P-udp4 & G3=$!
ip netns exec "$P-c" $S2TOOL stream 2001:db8:100::52 --port 9 --count 10 --sport 42000 --duration 8 --period 0.2 >/tmp/$P-udp6 & G4=$!
for set in "1" "2 3" "3" "" "1 2"; do
  sleep 1.6
  for f in 4 6; do balance $f $set; done
done
wait $G1 $G2 $G3 $G4 2>/dev/null || true
sleep 0.5
cap_stop
python3 - "$P" <<'EOF' >/tmp/$P-as22
import re, sys, collections
p = sys.argv[1]
seen = collections.defaultdict(set)
count = collections.Counter()
for ifc in ("wana", "wanb", "wanc"):
    for line in open(f"/tmp/{p}-cap-{ifc}"):
        m = re.search(r"(IP6?) \S+?\.(\d+) > (\S+)\.(9999|9): (Flags|UDP)", line)
        if m:
            key = (m.group(1), "tcp" if m.group(4) == "9999" else "udp", m.group(2))
            seen[key].add(ifc)
            count[key] += 1
multi = {k: v for k, v in seen.items() if len(v) > 1}
by = collections.Counter((k[0], k[1]) for k in seen)
print("flows", dict(by), "split", len(multi), "min_packets", min(count.values()) if count else 0)
EOF
r=$(cat /tmp/$P-as22)
note "$r; syn sockets: $(cat /tmp/$P-syn4) $(cat /tmp/$P-syn6); udp: $(cat /tmp/$P-udp4) $(cat /tmp/$P-udp6)"
check "40 flows observed (10 per family and protocol)" "\('IP', 'tcp'\): 10, \('IP', 'udp'\): 10|'IP', 'tcp'.: 10" "$r"
check "every packet of every flow left through a single uplink" "split 0 " "$r"
check "every SYN flow was retransmitted at least 3 times (4 SYNs)" "min_packets ([4-9]|[1-9][0-9])" "$r"
for f in 4 6; do balance $f 1 2 3; done

echo "== RELATED ICMP for inbound traffic through B, active set {A}"
for f in 4 6; do balance $f 1; done
for f in 4 6; do
  [ $f = 4 ] && RB=198.51.100.2 || RB=2001:db8:b::2
  icmp=$([ $f = 4 ] && echo icmp || echo icmp6)
  cap_start "$icmp and not ip6[40] == 135 and not ip6[40] == 136"
  nsi $PEER send "$RB" --port 8009 --count 3 >/dev/null
  cap_stop
  check "v$f port unreachable from the LAN host leaves through B only (a b c)" "^0 [1-9][0-9]* 0$" "$(cap_on wana) $(cap_on wanb) $(cap_on wanc)"
  note "$(head -1 /tmp/$P-cap-wanb | cut -d' ' -f2-)"
  cap_start "$icmp and not ip6[40] == 135 and not ip6[40] == 136"
  nsi $S2TOOL ttl "$RB" --port 8009 --ttl 2 --count 3 >/dev/null
  cap_stop
  check "v$f time exceeded generated by the router leaves through B only (a b c)" "^0 [1-9][0-9]* 0$" "$(cap_on wana) $(cap_on wanb) $(cap_on wanc)"
  note "$(head -1 /tmp/$P-cap-wanb | cut -d' ' -f2-)"
done

echo "== AS-31 core: path MTU discovery for a pinned outbound flow (provider A's core link MTU 1300)"
ip -n "$P-a" link set core mtu 1300
ip -n "$P-i" link set pa mtu 1300
# The server advertises a full-size MSS, so the client's segments hit the
# 1300-byte link inside provider A, which answers with ICMP errors.
ip -n "$P-i" route change 192.0.2.0/24 via 198.18.1.2 advmss 1460
ip -n "$P-i" -6 route change 2001:db8:a::/48 via 2001:db8:ff01::2 advmss 1440
for f in 4 6; do
  [ $f = 4 ] && D=198.18.100.61 || D=2001:db8:100::61
  for g in 4 6; do balance $g 1; done
  ip netns exec "$P-c" $S2TOOL bulk "$D" --bytes 300000 --timeout 10 >/tmp/$P-bulk$f &
  bp=$!; sleep 0.3
  for g in 4 6; do balance $g 2 3; done                      # A leaves the active set
  wait $bp || true
  check "v$f 300 kB transfer pinned to A completes across a 1300-byte link" '"error": null, "ok": true' "$(cat /tmp/$P-bulk$f)"
  # control: drop the ICMP errors on the router, a new transfer stalls
  nsr nft add table inet ctl
  nsr nft add chain inet ctl pre '{ type filter hook prerouting priority -300; policy accept; }'
  nsr nft add rule inet ctl pre icmp type destination-unreachable drop
  nsr nft add rule inet ctl pre icmpv6 type packet-too-big drop
  nsr ip route flush cache 2>/dev/null || true; nsc ip route flush cache 2>/dev/null || true
  nsc ip -6 route flush cache 2>/dev/null || true
  for g in 4 6; do balance $g 1; done
  r=$(nsc $S2TOOL bulk "$D" --bytes 300000 --timeout 4)
  check "v$f control: with the ICMP errors dropped the transfer fails" '"ok": false' "$r"
  nsr nft delete table inet ctl
done
summary
